### PR TITLE
documentation improvements

### PR DESCRIPTION
**Pull request by hazel-nut**
hello! @jgannondo asked me to do a copyedit of the docs here.

i did some rewriting and restructuring that i think improves the discoverability of the repo contents and presents the existing information in the docs in a more cohesive way.

the best way to review this PR is just to [view this branch in github directly](https://github.com/digitalocean/marketplace-partners/tree/hazel/copyedit). read the docs, follow links, click through the repository, and see how it feels. thoughts very warmly welcomed.

one note: i wanted to rename the `marketplace_validation` directory to `scripts` but @ryanpq suggested there might be deep links to those files elsewhere, so i held off on it for now. can anyone confirm?

### CODE REVIEW

**Comment by jgannondo** [comment]
@hazel-nut thanks for the PR. I think the only places we link out to the docs are on a handful of pages on marketplace.digitalocean.com. I'll check with Ryan as well.

**Comment by jgannondo** [comment]
@hazel-nut please do the rename. It's better to do it now while we have fewer vendors on the platform and there's no end-to-end API based submission of images. I can re-point the various links on the marketplace.digitalocean.com site once the changes are merged in.  // @ryanpq

**Comment by hazel-nut** [comment]
@jgannondo directory renamed in 18b123f and i merged in #63 :sparkles: i also went double checked all the links to make sure nothing broke in the reorg (everything looks good)

once i have an official :+1: i'll merge this in!

**Comment by ryanpq** [comment]
:+1:

**Pull request merged**
