### PR TITLE
Rq/issue 53

### PR DESCRIPTION
**Pull request by ryanpq**
#53 

Adding detection and version check for MongoDB to prevent SSPL versions from passing.

### CODE REVIEW

**Comment by ryanpq** [comment]
Tested against Ubuntu & CentOS with SSPL and non-SSPL versions of Mongo.  Works as expected and any version greater than 3.6.8, if installed, will trigger a failure.

**Comment by geekgonecrazy** [comment]
@ryanpq any reason why only < 3.6.8 ?  The Mongo 4.0.3 was the last release before they introduced SSPL license.  

I've opened PR #57 to correct this as seems to be falsely claiming 4.0.3 is SSPL.

**Comment by ryanpq** [comment]
Thanks for pointing this out.  We would need to confirm that 3.6.x series releases after 3.6.8 (and after Oct 16, 2018) are under the prior license.  If not we'll need to run separate comparisons for 3.x and 4.x releases rather than a simple > check on a single limit.

**Comment by geekgonecrazy** [comment]
Ah good point!  They likely wouldn't be based on the language there on their license page.

That definitely makes things a good bit more complicated.  So something like: 

if version <= 3.6.8 || version >= 4.0.0 && version <= 4.0.3

But in bash form

**Pull request merged**
